name: Update GitHub Activity

on:
  schedule:
    - cron: '* * * * *'

jobs:
  bulid:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: jamesgeorge007/github-activity-readme@master
      env:
        GITHUB_TOKEN: ${{ secrets.UPDATE_README }}
      with:
        COMMIT_MSG: 'docs: update github activity'
